---
- name: install Ruby packages 
  yum: name={{ item }} state=present
  with_items:
    - ruby
    - rake

- name: install gpg key for rvm
  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3

- name: install rvm
  shell: curl -sSL https://get.rvm.io | bash -s stable
