---
- name: install common packages 
  yum: name={{ item }} state=present
  with_items:
    - tar
    - bzip2
    - zip
    - unzip
    - htop
    - telnet

- name: generate SSH keys
  command: /usr/bin/ssh-keygen -A
